spring.application.name=ter

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mydb

spring.datasource.username=root
spring.datasource.password=vic6969!!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=dGfVyF1xCrFRwjJwRW/EgwFezpznf+ZUZHWPcYFfLSs=

proxmox.api.key=ncod93-2b8e-4c9a-9c1d-5f0e7a1b2c3d
proxmox.api.url=http://59.23.119.207:9071